global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: be_registry_backend_metrics
    metrics_path: /metrics
    static_configs:
      - targets:
          - be-trusted-registry-production.up.railway.app

  - job_name: be_registry_backend_health_probe
    metrics_path: /api/health
    static_configs:
      - targets:
          - be-trusted-registry-production.up.railway.app
